services:
    app:
        restart: unless-stopped
        build:
            context: .
        env_file:
            - ./.env
        volumes:
            - ./src/:/app/src/
            - ./config/:/app/config/
            - ./public/:/app/public/
        ports:
            - '${HTTP_PORT:-8080}:${HTTP_PORT:-8080}'
        logging:
            driver: 'json-file'
            options:
                max-size: '50m'
#        networks:
#            - web
#networks:
#    web:
#        external: true
#        name: web
